# Generated by Django 4.2.7 on 2025-12-27 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.TextField(blank=True, help_text='Tell us about your background, experience, and what drives you as an entrepreneur')),
                ('project_description', models.TextField(blank=True, help_text='Describe your project, the problem it solves, and your vision')),
                ('status', models.CharField(choices=[('pending', 'Applied - Pending Approval'), ('enrolled', 'Enrolled')], default='pending', help_text='Current status in the Nyota Catalyst program', max_length=20)),
                ('enrollment_date', models.DateField(blank=True, help_text='Date when the participant was enrolled in the program', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
