# Generated by Django 4.2.7 on 2025-12-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.TextField(blank=True, help_text='Tell us about your background, experience, and what drives you as an entrepreneur (max 2000 characters)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='project_description',
            field=models.TextField(blank=True, help_text='Describe your project, the problem it solves, and your vision (max 3000 characters)', max_length=3000),
        ),
    ]
