# Generated by Django 4.2.7 on 2025-12-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Applied - Pending Approval'), ('seeking_support', 'Seeking Support'), ('enrolled', 'Enrolled')], default='pending', help_text='Current status in the Nyota Catalyst program', max_length=20),
        ),
    ]
